main: me.delocaz.cmdx.CmdX
version: 1.0-dev
author: Delocaz
name: CmdX
commands:
  cx_tp:
    aliases: [tp, teleport, tele]
    description: "Teleports you to another player"
    usage: "/tp <player>"
    permission: cmdx.tp.tp
  cx_server:
    aliases: [server, serv]
    description: "Views information and does things relating to the server itself"
    usage: "/server <stop>"
    permission: cmdx.server.server
  cx_time:
    aliases: [time, t]
    description: "Sets the time in your current world"
    usage: "/time <day|night|noon|midnight|Nticks>"
    permission: cmdx.world.time
  cx_weather:
    aliases: [weather, rain, storm, w]
    description: "Sets the weather in your current world (if none specified)"
    usage: "/weather [on|off] [world]"
    permission: cmdx.world.weather
  cx_gamemode:
    aliases: [gamemode, gm, gmode, gamem]
    description: "Sets the gamemode for the specified player"
    usage: "/gamemode [player] [survival|creative|adventure]"
    permission: cmdx.player.gamemode
  cx_freeze:
    aliases: [freeze]
    description: "Freezes a player"
    usage: "/freeze [player]"
    permission: cmdx.mod.freeze
  cx_tphere:
    aliases: [tphere]
    description: "Teleports another player to you"
    usage: "/tphere <player>"
    permission: cmdx.tp.tphere
  cx_kick:
    aliases: [kick, boot]
    description: "Kicks a player from the server"
    usage: "/kick <player> [reason]"
    permission: cmdx.mod.kick
  cx_slap:
    aliases: [slap, bitchslap, punch]
    description: "Slaps a player, which sends them flying forwards"
    usage: "/slap [player] [power]"
    permission: cmdx.fun.slap
  cx_pinfo:
    aliases: [pinfo, info, whois]
    description: "Gives various informations about a player, will also work with offline players"
    usage: "/pinfo [player]"
    permission: cmdx.player.pinfo